# Configuration for running tool/generate_dart_api.dart
files_to_generate:
  # Misc
  - font-roboto/roboto.html
  - hydrolysis/hydrolysis-analyzer.html:
      omit_imports:
        - hydrolysis.html
  - prism-element/prism-highlighter.html:
      omit_imports:
        - prism-import.html
# Carbon
#  - carbon-route/carbon-location.html
#  - carbon-route/carbon-route-converter.html
#  - carbon-route/carbon-route.html
# Platinum
  - platinum-bluetooth/platinum-bluetooth-characteristic.html
  - platinum-bluetooth/platinum-bluetooth-device.html
  - platinum-bluetooth/platinum-bluetooth-elements.html
  - platinum-bluetooth/platinum-bluetooth-service.html
  - platinum-https-redirect/platinum-https-redirect.html
  - platinum-push-messaging/platinum-push-messaging.html:
     omit_imports:
      - promise-polyfill.html
     extra_imports:
      - "src/_utils.dart"
      - "dart:async"
     overrides:
      PlatinumPushMessaging:
       enable:
        - "/// Request push messaging to be enabled."
        - "Future enable() =>"
        - "  jsPromiseToFuture(jsElement.callMethod('enable',[]));"
       disable:
        - "/// Request push messaging to be disable."
        - "Future disable() =>"
        - "  jsPromiseToFuture(jsElement.callMethod('disable',[]));"

  - platinum-sw/platinum-sw-cache.html
  - platinum-sw/platinum-sw-elements.html
  - platinum-sw/platinum-sw-fetch.html
  - platinum-sw/platinum-sw-import-script.html
  - platinum-sw/platinum-sw-offline-analytics.html
  - platinum-sw/platinum-sw-register.html

# App
  - app-route/app-location.html  
  - app-route/app-route-converter-behavior.html  
  - app-route/app-route-converter.html  
  - app-route/app-route.html
  - app-localize-behavior/app-localize-behavior.html:
     overrides:
      AppLocalizeBehavior:
       localize: 
        - "  /// Translates a string to the current `language`. Any parameters to the"
        - "  /// string should be passed in order, as follows:"
        - "  /// `localize(stringKey, [param1Name, param1Value, param2Name, param2Value])`"
        - "  localize(String stringKey,[List<String> args]) => jsElement.callMethod('localize',[stringKey]..addAll((args==null ? [] : args) as List));"
  - app-pouchdb/app-pouchdb-database-behavior.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-pouchdb/app-pouchdb-document.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-pouchdb/app-pouchdb-query.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
     name_substitutions:
       query: queryConfig
  - app-pouchdb/app-pouchdb-index.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-pouchdb/app-pouchdb-conflict-resolution.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-pouchdb/app-pouchdb-sync.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-storage/app-network-status-behavior.html:
     omit_imports:
      - pouchdb.html
      - pouchdb.find.html
  - app-storage/app-storage-behavior.html:
      omit_imports:
        - promise-polyfill-lite.html
        - promise-polyfill.html
  - app-storage/app-localstorage/app-localstorage-document.html:
      name_substitutions:
       save: "save([key]) => //"
  - app-storage/app-indexeddb-mirror/app-indexeddb-mirror.html:
     omit_imports:
      - app-indexeddb-mirror-client.html
  - app-layout/app-box/app-box.html
  - app-layout/app-scroll-effects/app-scroll-effects-behavior.html
  - app-layout/app-scroll-effects/effects/blend-background.html
  - app-layout/app-scroll-effects/effects/fade-background.html
  - app-layout/app-scroll-effects/effects/material.html
  - app-layout/app-scroll-effects/effects/parallax-background.html
  - app-layout/app-scroll-effects/effects/resize-snapped-title.html
  - app-layout/app-scroll-effects/effects/resize-title.html
  - app-layout/app-scroll-effects/effects/waterfall.html
  - app-layout/app-drawer/app-drawer.html
  - app-layout/app-scroll-effects/app-scroll-effects.html
  - app-layout/app-drawer-layout/app-drawer-layout.html  
  - app-layout/app-scrollpos-control/app-scrollpos-control.html
  - app-layout/app-header/app-header.html
  - app-layout/app-toolbar/app-toolbar.html
  - app-layout/app-header-layout/app-header-layout.html  
  - app-layout/helpers/helpers.html
  - app-layout/app-scroll-effects/effects/blend-background.html
  - app-layout/app-scroll-effects/effects/fade-background.html
  - app-layout/app-scroll-effects/effects/material.html
  - app-layout/app-scroll-effects/effects/parallax-background.html
  - app-layout/app-scroll-effects/effects/resize-snapped-title.html
  - app-layout/app-scroll-effects/effects/resize-title.html
  - app-layout/app-scroll-effects/effects/waterfall.html
#   Google Web Components https://elements.polymer-project.org/browse?package=google-web-components
  - polymerfire/firebase-common-behavior.html:
      omit_imports:
        - firebase.html
  - polymerfire/firebase-app.html:
      omit_imports:
        - firebase.html
  - polymerfire/firebase-auth.html:
      omit_imports:
        - firebase.html
  - polymerfire/firebase-database-behavior.html:
      omit_imports:
        - firebase.html
  - polymerfire/firebase-document.html:
      omit_imports:
        - firebase.html
      name_substitutions:
       save: "save([String parentPath, key]) => //"
  - polymerfire/firebase.html:
      omit_imports:
        - firebase.html
  - polymerfire/firebase-query.html:
      omit_imports:
        - firebase.html
      name_substitutions:
        query: queryObject

#  - firebase-element/firebase-auth.html:
#      omit_imports:
#        - firebase.html
#  - firebase-element/firebase-query-behavior.html:
#      omit_imports:
#        - firebase.html
#      name_substitutions:
#        query: queryObject
#  - firebase-element/firebase-collection.html:
#      omit_imports:
#        - firebase.html
#      name_substitutions:
#        query: queryObject
#        remove: firebaseRemove
#        add: firebaseAdd
#  - firebase-element/firebase-document.html:
#      omit_imports:
#        - firebase.html
#      name_substitutions:
#        query: queryObject
  - google-analytics/google-analytics.html
  - google-analytics/google-analytics-chart.html:
      omit_imports:
        - promise-polyfill-lite.html
  - google-analytics/google-analytics-dashboard.html:
      name_substitutions:
        query: queryObject
  - google-analytics/google-analytics-date-selector.html
  - google-analytics/google-analytics-loader.html:
      omit_imports:
        - promise-polyfill-lite.html
  - google-analytics/google-analytics-query.html
  - google-analytics/google-analytics-view-selector.html:
      omit_imports:
        - account-summaries-import.html
  - google-apis/google-apis.html
  - google-apis/google-client-loader.html
  - google-apis/google-js-api.html
  - google-apis/google-legacy-loader.html
  - google-apis/google-maps-api.html
  - google-apis/google-plusone-api.html
  - google-apis/google-realtime-api.html
  - google-apis/google-youtube-api.html
  - google-calendar/google-calendar.html
  - google-castable-video/google-castable-video.html:
      omit_imports:
        - google-cast-sender-api.html
      name_substitutions:
       pause: "pause([cast]) => //"
       play: "play([cast]) => //"
  - google-chart/google-chart.html:
      omit_imports:
        - promise-polyfill-lite.html
#  - google-chart/charts-loader.html:
#      omit_imports:
#        - promise-polyfill-lite.html
  - google-chart/google-chart-loader.html:
      omit_imports:
        - promise-polyfill-lite.html
        - chart-loader.html
  - google-feeds/google-feeds.html:
      name_substitutions:
        query: queryObject
  - google-hangout-button/google-hangout-button.html
  - google-map/google-map.html:
     name_substitutions:
      clear: clearMarkers
  - google-map/google-map-directions.html
  - google-map/google-map-marker.html
  - google-map/google-map-point.html
  - google-map/google-map-poly.html
  - google-map/google-map-search.html:
      name_substitutions:
        query: queryObject
  - google-sheets/google-sheets.html
  - google-signin/google-signin.html:
      omit_imports:
        - google-icons.html
  - google-signin/google-signin-aware.html
  - google-streetview-pano/google-streetview-pano.html
  - google-url-shortener/google-url-shortener.html
  - google-youtube/google-youtube.html
  - google-youtube-upload/google-youtube-upload.html

  # Gold Elements https://elements.polymer-project.org/browse?package=gold-elements
  - gold-cc-cvc-input/gold-cc-cvc-input.html
  - gold-cc-expiration-input/date-input.html:
     name_substitutions:
      validate: "validate([_]) => //"
  - gold-cc-expiration-input/date-validator.html
  - gold-cc-expiration-input/gold-cc-expiration-input.html
  - gold-cc-input/gold-cc-input.html:
     name_substitutions:
      validate: "validate([_]) => //"
  - gold-email-input/gold-email-input.html
  - gold-phone-input/gold-phone-input.html
  - gold-zip-input/gold-zip-input.html
  - gold-zip-input/zip-validator.html

  # Iron Elements https://elements.polymer-project.org/browse?package=iron-elements
  - iron-a11y-announcer/iron-a11y-announcer.html:
      name_substitutions:
          created: create
  - iron-a11y-keys/iron-a11y-keys.html
  - iron-a11y-keys-behavior/iron-a11y-keys-behavior.html:
      name_substitutions:
        keyBindings: instanceKeyBindings
  - iron-ajax/iron-ajax.html
  - iron-ajax/iron-request.html:
      omit_imports:
        - promise-polyfill-lite.html
  - iron-autogrow-textarea/iron-autogrow-textarea.html:
      name_substitutions:
       validate: "validate([_]) => //"
  - iron-behaviors/iron-button-state.html
  - iron-behaviors/iron-control-state.html
  - iron-checked-element-behavior/iron-checked-element-behavior.html
  - iron-collapse/iron-collapse.html
  - iron-component-page/iron-component-page.html
  - iron-demo-helpers/demo-snippet.html
  - iron-demo-helpers/demo-pages-shared-styles.html
  - iron-doc-viewer/iron-doc-viewer.html
  - iron-doc-viewer/iron-doc-viewer-styles.html
  - iron-doc-viewer/iron-doc-property.html
  - iron-doc-viewer/iron-doc-property-styles.html
  - iron-dropdown/iron-dropdown.html:
      omit_imports:
        - iron-dropdown-scroll-manager.html
  - iron-fit-behavior/iron-fit-behavior.html
  - iron-flex-layout/iron-flex-layout.html
  - iron-flex-layout/iron-flex-layout-classes.html
  - iron-flex-layout/classes/iron-flex-layout.html
  - iron-flex-layout/classes/iron-shadow-flex-layout.html
  - iron-form/iron-form.html
  - iron-form-element-behavior/iron-form-element-behavior.html
  - iron-icon/iron-icon.html
  - iron-icons/av-icons.html
  - iron-icons/communication-icons.html
  - iron-icons/device-icons.html
  - iron-icons/editor-icons.html
  - iron-icons/hardware-icons.html
  - iron-icons/image-icons.html
  - iron-icons/iron-icons.html
  - iron-icons/maps-icons.html
  - iron-icons/notification-icons.html
  - iron-icons/places-icons.html
  - iron-icons/social-icons.html
  - iron-iconset/iron-iconset.html
  - iron-iconset-svg/iron-iconset-svg.html
  - iron-image/iron-image.html
  - iron-input/iron-input.html:
      name_substitutions:
       validate: "validate([_]) => //"
  - iron-jsonp-library/iron-jsonp-library.html
  - iron-label/iron-label.html:
      name_substitutions:
        for: labelFor
  - iron-list/iron-list.html:
      omit_imports:
        - templatizer.html # Part of `polymer_interop.dart`
  - iron-location/iron-location.html:
      name_substitutions:
        query: locationQuery
  - iron-location/iron-query-params.html
  - iron-localstorage/iron-localstorage.html
  - iron-media-query/iron-media-query.html:
      name_substitutions:
        query: mediaQuery
  - iron-menu-behavior/iron-menu-behavior.html
  - iron-menu-behavior/iron-menubar-behavior.html
  - iron-meta/iron-meta.html
  - iron-overlay-behavior/iron-overlay-behavior.html:
      omit_imports:
        - iron-overlay-manager.html
  - iron-overlay-behavior/iron-overlay-backdrop.html:
      omit_imports:
        - iron-overlay-manager.html
  - iron-pages/iron-pages.html
  - iron-page-url/iron-page-url.html:
      name_substitutions:
        query: queryString
  - iron-range-behavior/iron-range-behavior.html:
      type_overrides:
        IronRangeBehavior:
          value:
            type: any
  - iron-resizable-behavior/iron-resizable-behavior.html
  - iron-scroll-target-behavior/iron-scroll-target-behavior.html
  - iron-scroll-threshold/iron-scroll-threshold.html
  - iron-selector/iron-multi-selectable.html
  - iron-selector/iron-selectable.html:
      type_overrides:
        IronSelectableBehavior:
          selected:
            type: any
  - iron-selector/iron-selection.html
  - iron-selector/iron-selector.html
  - iron-signals/iron-signals.html
  - iron-swipeable-container/iron-swipeable-container.html
  - iron-test-helpers/iron-test-helpers.html
  - iron-test-helpers/mock-interactions.html
  - iron-test-helpers/test-helpers.html
  - iron-validatable-behavior/iron-validatable-behavior.html
  - iron-validator-behavior/iron-validator-behavior.html

  # Molecules https://elements.polymer-project.org/browse?package=molecules
  - marked-element/marked-element.html:
      omit_imports:
        - marked-import.html

  # Neon Elements https://elements.polymer-project.org/browse?package=neon-elements
  - neon-animation/animations/cascaded-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/fade-in-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/fade-out-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/hero-animation.html:
      omit_imports:
        - web-animations.html
      name_substitutions:
        complete: "complete([config]) => //"
  - neon-animation/animations/opaque-animation.html:
      omit_imports:
        - web-animations.html
      name_substitutions:
        complete: "complete([config]) => //"
  - neon-animation/animations/reverse-ripple-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/ripple-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/scale-down-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/scale-up-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-from-bottom-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-from-top-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-down-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-from-left-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-from-right-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-left-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-right-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/slide-up-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/animations/transform-animation.html:
      omit_imports:
        - web-animations.html
  - neon-animation/neon-animatable.html
  - neon-animation/neon-animatable-behavior.html
  - neon-animation/neon-animated-pages.html
  - neon-animation/neon-animation.html:
      omit_imports:
        - neon-animations.html
  - neon-animation/neon-animation-behavior.html
  - neon-animation/neon-animation-runner-behavior.html
  - neon-animation/neon-shared-element-animatable-behavior.html
  - neon-animation/neon-shared-element-animation-behavior.html

  # Paper Elements https://elements.polymer-project.org/browse?package=paper-elements
  - paper-badge/paper-badge.html:
      name_substitutions:
        for: forId
  - paper-behaviors/paper-button-behavior.html
  - paper-behaviors/paper-checked-element-behavior.html
  - paper-behaviors/paper-inky-focus-behavior.html
  - paper-behaviors/paper-ripple-behavior.html
  - paper-button/paper-button.html
  - paper-card/paper-card.html
  - paper-checkbox/paper-checkbox.html
  - paper-dialog/paper-dialog.html
  - paper-dialog-behavior/paper-dialog-behavior.html
  - paper-dialog-behavior/paper-dialog-shared-styles.html
  - paper-dialog-scrollable/paper-dialog-scrollable.html
  - paper-drawer-panel/paper-drawer-panel.html
  - paper-dropdown-menu/paper-dropdown-menu.html
  - paper-dropdown-menu/paper-dropdown-menu-light.html
  - paper-dropdown-menu/paper-dropdown-menu-icons.html  
  - paper-dropdown-menu/paper-dropdown-menu-shared-styles.html
  - paper-fab/paper-fab.html
  - paper-header-panel/paper-header-panel.html
  - paper-icon-button/paper-icon-button.html
  - paper-input/paper-input.html
  - paper-input/paper-input-addon-behavior.html
  - paper-input/paper-input-behavior.html:
      type_overrides:
        PaperInputBehavior:
          value:
            type: any
  - paper-input/paper-input-char-counter.html
  - paper-input/paper-input-container.html
  - paper-input/paper-input-error.html
  - paper-input/paper-textarea.html
  - paper-item/paper-icon-item.html
  - paper-item/paper-item.html
  - paper-item/paper-item-behavior.html
  - paper-item/paper-item-body.html
  - paper-item/paper-item-shared-styles.html
  - paper-material/paper-material.html
  - paper-material/paper-material-shared-styles.html
  - paper-menu/paper-menu.html
  - paper-menu/paper-menu-shared-styles.html
  - paper-listbox/paper-listbox.html
  - paper-menu/paper-submenu.html
  - paper-menu-button/paper-menu-button.html
  - paper-menu-button/paper-menu-button-animations.html:
      omit_imports:
        - web-animations.html
  - paper-progress/paper-progress.html
  - paper-radio-button/paper-radio-button.html
  - paper-radio-group/paper-radio-group.html
  - paper-ripple/paper-ripple.html:
      name_substitutions:
       animate: "validate([_,__]) => //"
  - paper-scroll-header-panel/paper-scroll-header-panel.html:
      name_substitutions:
       scroll: "scrollAt"
  - paper-slider/paper-slider.html
  - paper-spinner/paper-spinner.html
  - paper-spinner/paper-spinner-lite.html
  - paper-spinner/paper-spinner-behavior.html
  - paper-spinner/paper-spinner-styles.html
  - paper-styles/color.html
  - paper-styles/default-theme.html
  - paper-styles/demo-pages.html
  - paper-styles/paper-styles.html
  - paper-styles/paper-styles-classes.html
  - paper-styles/shadow.html
  - paper-styles/typography.html
  - paper-styles/classes/global.html
  - paper-styles/classes/shadow.html
  - paper-styles/classes/shadow-layout.html
  - paper-styles/classes/typography.html
  - paper-tabs/paper-tab.html
  - paper-tabs/paper-tabs.html
  - paper-tabs/paper-tabs-icons.html
  - paper-toast/paper-toast.html
  - paper-toggle-button/paper-toggle-button.html
  - paper-toolbar/paper-toolbar.html
  - paper-tooltip/paper-tooltip.html:
      name_substitutions:
        for: forId
        offset: tooltipOffset

# TODO(jakemac): https://github.com/dart-lang/polymer_elements/issues/12
#  # Platinum Elements https://elements.polymer-project.org/browse?package=platinum-elements
#  - platinum-push-messaging/platinum-push-messaging.html:
#      omit_imports:
#        - promise-polyfill.html
#  - platinum-sw/platinum-sw-cache.html
#  - platinum-sw/platinum-sw-fetch.html
#  - platinum-sw/platinum-sw-import-script.html
#  - platinum-sw/platinum-sw-register.html
files_to_load:
  - package:polymer_interop/src/js/debug/src/lib/template/templatizer.html
deletion_patterns:
  - metadata\.html$
  - /index\.html$
  - demo\.html$
  - demos$
  - demo$
  - README\.md$
  - ^polymer$
  - ^webcomponentsjs$
  - .gitignore$
  - .travis.yml$
  - .github
  - site$
  - CONTRIBUTING\.md$
