name: polymer_elements
version: 1.0.0-rc.1
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer polymer-elements for Dart
homepage: https://www.dartlang.org/polymer/
dependencies:
  browser: ^0.10.0
  polymer_interop: ^1.0.0-rc.1
  web_components: ^0.12.0
  reflectable: ^0.3.1
dev_dependencies:
  custom_element_apigen: ^0.2.0+2
  html5lib: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  yaml: ">=1.0.0 <3.0.0"
  test: ^0.12.0
  polymer: ^1.0.0-rc.2

environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- web_components:
    $include: test/*_test.html
- reflectable:
    entry_points:
    - test/iron_a11y_keys_behavior_test.dart
    - test/iron_behavior_active_state_test.dart
    - test/iron_behavior_disabled_state_test.dart
    - test/iron_behavior_focused_state_test.dart
    - test/iron_checked_element_behavior_test.dart
    - test/iron_fit_behavior_test.dart
    - test/iron_form_test.dart
    - test/iron_list_basic_test.dart
    - test/iron_list_hidden_test.dart
    - test/iron_list_mutations_test.dart
    - test/iron_list_physical_count_test.dart
    - test/iron_list_selection_test.dart
    - test/iron_menu_behavior_test.dart
    - test/iron_menubar_behavior_test.dart
    - test/iron_overlay_behavior_test.dart
    - test/iron_range_behavior_test.dart
    - test/iron_resizable_behavior_basic_test.dart
    - test/iron_resizable_behavior_test.dart
    - test/iron_validatable_behavior_test.dart
    - test/iron_validator_behavior_test.dart
    - test/neon_animated_pages_test.dart
    - test/paper_button_behavior_test.dart
    - test/paper_dialog_behavior_test.dart
    - test/paper_inky_focus_behavior_test.dart
    - test/paper_scroll_header_panel_basic_test.dart
    - test/paper_scroll_header_panel_header_state_test.dart
    - test/paper_scroll_header_panel_scroll_test.dart
    - test/paper_tooltip_test.dart
- test/pub_serve:
    $include: test/**_test{.*,}.dart

environment:
  sdk: ">=1.8.0 <2.0.0"
