name: polymer_elements
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer polymer-elements for Dart
homepage: https://www.dartlang.org/polymer/
dependencies:
  browser: any
  polymer_interop: ^0.2.0
  web_components: ^0.12.0
dev_dependencies:
  custom_element_apigen: ^0.2.0
  html5lib: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  yaml: ">=1.0.0 <3.0.0"
  test: ^0.12.0
  polymer:
    git:
      ref: behaviors
      url: https://github.com/dart-lang/polymer-dart.git

dependency_overrides:
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
  custom_element_apigen:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/custom-element-apigen.git
  reflectable:
    path: ../reflectable/reflectable
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- web_components:
    $include: test/*_test.html
- test/pub_serve:
    $include: test/**_test{.*,}.dart
