name: polymer_elements_demo
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer polymer-elements for Dart examples.
homepage: https://www.dartlang.org/polymer/
dependencies:
  browser: any
  polymer:
    git:
      url: git@github.com:dart-lang/polymer-dart.git
      ref: 1.0.0-rc.1
  polymer_elements:
    path: ..
  polymer_interop: ^0.2.0-rc1
  reflectable: ^0.2.1
  web_components: ^0.12.0
dev_dependencies:
  github: '>=2.2.3+1 <3.0.0'
  path: '>=1.3.6 <2.0.0'
  test: ^0.12.0
  yaml: ">=1.0.0 <3.0.0"
  quiver: '>=0.21.4 <0.22.0'
  crypto: '>=0.9.1 <0.10.0'
dependency_overrides:
  reflectable: 0.2.1
  polymer_interop:
    git:
      ref: 0.2.0-rc1
      url: https://github.com/dart-lang/polymer_interop.git
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- web_components:
    entry_points:
    #- web/chartjs_element/index.html TODO(zoechi) element not available
    - web/firebase_element/index.html
    - web/gold_cc_cvc_input/index.html # TODO(zoechi) issues #64
    - web/gold_cc_expiration_input/index.html
    - web/gold_cc_input/index.html # TODO(zoechi) issues #64
    - web/gold_email_input/index.html
    - web/gold_phone_input/index.html
    - web/gold_zip_input/index.html
    - web/google_analytics/index.html # TODO(zoechi) issues #67
    - web/google_apis/index.html # TODO(zoechi) issues #65
    - web/google_calendar/index.html # TODO(zoechi) issues #67
    - web/google_castable_video/index.html # TODO(zoechi) issues (see code)
    - web/google_chart/index.html # TODO(zoechi) issues #66
    #- web/google_domain_user_picker/index.html TODO(zoechi) element not available
    #- web/google_drive/index.html TODO(zoechi) element not available
    - web/google_feeds/index.html
    - web/google_hangout_button/index.html
    - web/google_map/index.html
    #- web/google_recaptcha/index.html # TODO(zoechi) element not available
    - web/google_sheets/index.html # TODO(zoechi) issues #68
    - web/google_signin/index.html # TODO(zoechi) issues #67
    - web/google_streetview_pano/index.html
    - web/google_url_shortener/index.html
    - web/google_youtube/index.html
    - web/google_youtube_upload/index.html
    - web/iron_a11y_announcer/index.html
    - web/iron_a11y_keys/index.html
    - web/iron_a11y_keys_behavior/index.html # TODO(zoechi) issues #70
    - web/iron_ajax/index.html
    - web/iron_autogrow_textarea/index.html
    - web/iron_behaviors/index.html
    - web/iron_checked_element_behavior/index.html # TODO(zoechi) element not available #71
    - web/iron_collapse/index.html
    - web/iron_component_page/index.html
    - web/iron_doc_viewer/index.html
    - web/iron_dropdown/index.html # TODO(zoechi) doesn't work (position is off), I don't know how to port code in `expand_animation.dart`
    - web/iron_fit_behavior/index.html
    - web/iron_flex_layout/index.html
    - web/iron_form/index.html # TODO(zoechi) issues dart-lang/polymer-dart#598 (should be fixed)
    - web/iron_form_element_behavior/index.html # TODO(zoechi) issues #72
    - web/iron_icon/index.html
    - web/iron_icons/index.html
    - web/iron_iconset/index.html
    - web/iron_iconset_svg/index.html
    - web/iron_image/index.html
    - web/iron_input/index.html
    - web/iron_jsonp_library/index.html
    # - web/iron_label/index.html # TODO(zoechi) element not available
    - web/iron_list/index.html # TODO(zoechi) items height wrong when demo is inside an element
    - web/iron_list/external_content.html # for all 3 examples
    - web/iron_list/selection.html
    #- web/iron_localstorage/index.html # TODO(zoechi) issues dart-lang/polymer-dart#600
    - web/iron_media_query/index.html
    - web/iron_menu_behavior/index.html

- reflectable:
    entry_points:
    #- web/chartjs_element/index.dart
    - web/firebase_element/index.dart
    - web/gold_cc_cvc_input/index.dart
    - web/gold_cc_expiration_input/index.dart
    - web/gold_cc_input/index.dart
    - web/gold_email_input/index.dart
    - web/gold_phone_input/index.dart
    - web/gold_zip_input/index.dart
    - web/google_analytics/index.dart
    - web/google_apis/index.dart
    - web/google_calendar/index.dart
    - web/google_castable_video/index.dart
    - web/google_chart/index.dart
    #- web/google_domain_user_picker/index.dart
    #- web/google_drive/index.dart
    - web/google_feeds/index.dart
    - web/google_hangout_button/index.dart
    - web/google_map/index.dart
    #- web/google_recaptcha/index.dart
    - web/google_sheets/index.dart
    - web/google_signin/index.dart
    - web/google_streetview_pano/index.dart
    - web/google_url_shortener/index.dart
    - web/google_youtube/index.dart
    - web/google_youtube_upload/index.dart
    - web/iron_a11y_announcer/index.dart
    - web/iron_a11y_keys/index.dart
    - web/iron_a11y_keys_behavior/index.dart
    - web/iron_ajax/index.dart
    - web/iron_autogrow_textarea/index.dart
    - web/iron_behaviors/index.dart
    - web/iron_checked_element_behavior/index.dart
    - web/iron_collapse/index.dart
    - web/iron_component_page/index.dart
    - web/iron_doc_viewer/index.dart
    - web/iron_dropdown/index.dart
    - web/iron_fit_behavior/index.dart
    - web/iron_flex_layout/index.dart
    - web/iron_flex_layout/index.dart
    - web/iron_form/index.dart
    - web/iron_form_element_behavior/index.dart
    - web/iron_icon/index.dart
    - web/iron_icons/index.dart
    - web/iron_iconset/index.dart
    - web/iron_iconset_svg/index.dart
    - web/iron_image/index.dart
    - web/iron_input/index.dart
    - web/iron_jsonp_library/index.dart
    # - web/iron_label/index.dart
    - web/iron_list/index.dart
    - web/iron_list/external_content.dart
    - web/iron_list/selection.dart
    #- web/iron_localstorage/index.dart
    - web/iron_media_query/index.dart
    - web/iron_menu_behavior/index.dart


- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
